name: Context
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      RANCH: main
    steps:
      - run: echo "${ BRANCH }"
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
